// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7S2TSal1m-C246lbBq1sE7U2_LhVlaes',
    appId: '1:543172942770:web:ec35ebdec67b7275f122ab',
    messagingSenderId: '543172942770',
    projectId: 'polynomial-calculator-ken01',
    authDomain: 'polynomial-calculator-ken01.firebaseapp.com',
    storageBucket: 'polynomial-calculator-ken01.appspot.com',
    measurementId: 'G-SWPXJK8J49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTA4joGoBLHMpN_wxrkHdWtToWxcLTeI8',
    appId: '1:543172942770:android:e6d240468988526cf122ab',
    messagingSenderId: '543172942770',
    projectId: 'polynomial-calculator-ken01',
    storageBucket: 'polynomial-calculator-ken01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQUF25IZ_55YzdpaAs8bTrIQR1RKyh3F4',
    appId: '1:543172942770:ios:f76e646783b67cbaf122ab',
    messagingSenderId: '543172942770',
    projectId: 'polynomial-calculator-ken01',
    storageBucket: 'polynomial-calculator-ken01.appspot.com',
    iosBundleId: 'com.example.polynomialCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQUF25IZ_55YzdpaAs8bTrIQR1RKyh3F4',
    appId: '1:543172942770:ios:f76e646783b67cbaf122ab',
    messagingSenderId: '543172942770',
    projectId: 'polynomial-calculator-ken01',
    storageBucket: 'polynomial-calculator-ken01.appspot.com',
    iosBundleId: 'com.example.polynomialCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7S2TSal1m-C246lbBq1sE7U2_LhVlaes',
    appId: '1:543172942770:web:dfbb4c2177d87921f122ab',
    messagingSenderId: '543172942770',
    projectId: 'polynomial-calculator-ken01',
    authDomain: 'polynomial-calculator-ken01.firebaseapp.com',
    storageBucket: 'polynomial-calculator-ken01.appspot.com',
    measurementId: 'G-S293GC8B39',
  );
}
